// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.clinicasmanager.entity;

import ar.com.clinicasmanager.entity.NodoDiagnostico;
import javax.persistence.Entity;

privileged aspect NodoDiagnostico_Roo_Jpa_Entity {
    
    declare @type: NodoDiagnostico: @Entity;
    
    public NodoDiagnostico.new() {
        super();
    }

}
