// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.clinicasmanager.entity;

import ar.com.clinicasmanager.entity.Paciente;
import javax.persistence.Entity;

privileged aspect Paciente_Roo_Jpa_Entity {
    
    declare @type: Paciente: @Entity;
    
    public Paciente.new() {
        super();
    }

}
