package ar.com.clinicasmanager.entity.enums;

public enum PermisosUsuario { 
    ADMINISTRAR_GRUPOS,
    ADMINISTRAR_USUARIOS,
    ADMINISTRAR_FICHAS,
    CONFIGURAR_FICHAS,
    VER_CONSULTAS,
    ELIMINAR_CONSULTAS,    
    BUSCAR_PACIENTES,
    BUSCAR_CONSULTAS,
    CREAR_DATOS_FILIATORIOS,
    EDITAR_DATOS_FILIATORIOS,
    ELIMINAR_PACIENTE,
    CREAR_CONSULTA,
    ADMINISTRAR_EVOLUCION,
    ADMINISTAR_INTERNACION,
    ADMINISTRAR_PLAN,
    ADMINISTRAR_CIRUGIA,
    ADMINISTRAR_ALTA,
    ADMINISTRAR_DIAGNOSTICO,
    ELIMINAR_LESION,
    ELIMINAR_TRATAMIENTO,
    ADMINISTRAR_TRATAMIENTO,
    ADMINISTRAR_IMAGENES,
    USAR_FICHA,
    USAR_SCORE
    
}